# Generated by Django 3.2.6 on 2021-08-27 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20210819_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(default='static/tasks/images/default.png', upload_to='task_images'),
        ),
    ]
