# Generated by Django 3.2.6 on 2021-08-26 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='static/user/images', upload_to='user/images/default.png'),
        ),
    ]
