# Generated by Django 3.2.6 on 2021-08-26 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='static/user/images/default.png', upload_to='user/images/'),
        ),
    ]
